### PR TITLE
 feat: add cli, system keychain & secure input

### PR DESCRIPTION
**Pull request by panekj**

### CODE REVIEW

**Comment by dzhou121** [comment]
I think it’s fine to be clear text when pasting the token, other than that it looks fine.

**Comment by panekj** [comment]
> I think it’s fine to be clear text when pasting the token, other than that it looks fine.

Maybe, but tokens are sensitive in nature and I would like to not present different behaviour from other cli tools with auth.

**Comment by dzhou121** [comment]
Cargo login is clear text for one I can see.

**Comment by panekj** [comment]
`git` and `ssh` hide input

**Comment by dzhou121** [comment]
I think you hide a password which you set, but no need for a token generated for you.

**Pull request merged**
